~*
~*  This job builds the DUAL product. It edits the dual-state
~*  binaries into the PRODUCT file and adds a directive to the
~*  DIRFILE file specifying the library number associated with
~*  them.
~*
DUAL.
$USER,INSTALL,${../site.cfg:PASSWORDS:INSTALL:INSTALL}.
$NORERUN.
$SETTL,*.
$SETASL,*.
$SETJSL,*.
$COPYBR,INPUT,DIR.
$ASSIGN,${1},TAPE,D=GE,LB=KU,F=I,PO=R.
$COPY,TAPE,LGO.
$REWIND,LGO,DIR.
$ATTACH,PRODUCT,DIRFILE/M=W,WB.
$LIBEDIT,P=PRODUCT,B=LGO,I=0,C.
$LIBEDIT,P=DIRFILE,B=DIR,I=0,C.
***
*** DUAL COMPLETE
***
EXIT.
***
*** DUAL FAILED
***
~eor
DUAL
*ADD LIB22,PP/VER-ABS/FASLAVE
